defmodule Euler.Problems.Zero.Two do
  @moduledoc """
  Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting
  with 1 and 2, the first 10 terms will be:

  1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

  By considering the terms in the Fibonacci sequence whose values do not exceed four million, find
  the sum of the even-valued terms.
  """
  @behaviour Euler.Problems.Behaviour

  alias Euler.Helpers.Fib

  @impl Euler.Problems.Behaviour
  def exec(limit) do
    Fib.stream()
    |> Stream.take_while(fn n -> n < limit end)
    |> Stream.filter(fn n -> rem(n, 2) == 0 end)
    |> Enum.to_list()
    |> Enum.reduce(&+/2)
  end
end
